// ============================================================
//  ArcenPay Internal Core — Contract ABIs
//  ABI definitions for all protocol contracts
//  NOTE: These are simplified ABIs for SDK usage.
//  Full ABIs are auto-generated by Hardhat compilation.
// ============================================================

export const SubscriptionRegistryABI = [
  // Core functions
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address" },
      { name: "planId", type: "uint256" },
      { name: "duration", type: "uint64" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renew",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "extension", type: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changePlan",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "newPlanId", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isValid",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expiresAt",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlanFeatures",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      { name: "planId", type: "uint256" },
      { name: "planTier", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWalletSubscription",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "importSubscription",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "planId", type: "uint256" },
      { name: "expiration", type: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeMigration",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasActiveSubscription",
    inputs: [{ name: "wallet", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedBillers",
    inputs: [{ name: "biller", type: "address" }],
    outputs: [{ name: "isAuthorized", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setCrossChainTransports",
    inputs: [
      { name: "axelarTransport", type: "address" },
      { name: "ccipTransport", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "dispatchCrossChainUpdate",
    inputs: [
      { name: "tokenId", type: "uint256" },
      { name: "destinationChainId", type: "uint256" },
      { name: "refundAddress", type: "address" },
    ],
    outputs: [
      { name: "messageId", type: "bytes32" },
      { name: "routeUsed", type: "uint8" },
    ],
    stateMutability: "payable",
  },
  // Events
  {
    type: "event",
    name: "SubscriptionMinted",
    inputs: [
      { name: "subscriber", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "expiration", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionRenewed",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "newExpiration", type: "uint64", indexed: false },
      { name: "amountPaid", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionCancelled",
    inputs: [{ name: "tokenId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "SubscriptionPlanChanged",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "previousPlanId", type: "uint256", indexed: true },
      { name: "newPlanId", type: "uint256", indexed: true },
      { name: "expiration", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BillingSuccess",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CrossChainDispatchRequested",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "destinationChainId", type: "uint256", indexed: true },
      { name: "route", type: "uint8", indexed: true },
      { name: "messageId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CrossChainFallbackTriggered",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "destinationChainId", type: "uint256", indexed: true },
      { name: "primaryError", type: "bytes", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubscriptionImported",
    inputs: [
      { name: "subscriber", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "expiration", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RegistryMigrationFinalized",
    inputs: [],
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
    ],
  },
] as const;

export const PlanFactoryABI = [
  {
    type: "function",
    name: "createPlan",
    inputs: [
      { name: "name", type: "string" },
      { name: "tier", type: "string" },
      { name: "price", type: "uint256" },
      { name: "billingInterval", type: "uint32" },
      { name: "acceptedToken", type: "address" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [{ name: "planId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPlanFor",
    inputs: [
      { name: "provider", type: "address" },
      { name: "name", type: "string" },
      { name: "tier", type: "string" },
      { name: "price", type: "uint256" },
      { name: "billingInterval", type: "uint32" },
      { name: "acceptedToken", type: "address" },
      { name: "metadataURI", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [{ name: "planId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPlan",
    inputs: [{ name: "planId", type: "uint256" }],
    outputs: [
      {
        name: "plan",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "provider", type: "address" },
          { name: "name", type: "string" },
          { name: "tier", type: "string" },
          { name: "price", type: "uint256" },
          { name: "billingInterval", type: "uint32" },
          { name: "acceptedToken", type: "address" },
          { name: "active", type: "bool" },
          { name: "metadataURI", type: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProviderPlans",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "planIds", type: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isProvider",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonces",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlanCreated",
    inputs: [
      { name: "planId", type: "uint256", indexed: true },
      { name: "provider", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "price", type: "uint256", indexed: false },
      { name: "billingInterval", type: "uint32", indexed: false },
    ],
  },
  {
    type: "function",
    name: "deactivatePlan",
    inputs: [{ name: "planId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePlan",
    inputs: [
      { name: "planId", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updatePlanFor",
    inputs: [
      { name: "provider", type: "address" },
      { name: "planId", type: "uint256" },
      { name: "price", type: "uint256" },
      { name: "metadataURI", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "PlanDeactivated",
    inputs: [{ name: "planId", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "PlanUpdated",
    inputs: [{ name: "planId", type: "uint256", indexed: true }],
  },
] as const;

export const ERC7579AutopayModuleABI = [
  {
    type: "function",
    name: "onInstall",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onUninstall",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "execute",
    inputs: [
      { name: "account", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isInitialized",
    inputs: [{ name: "smartAccount", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getConfig",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "maxAmount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "interval", type: "uint32" },
          { name: "startTime", type: "uint64" },
          { name: "planId", type: "uint256" },
          { name: "maxTotalAmount", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateConfig",
    inputs: [
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "maxAmount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "interval", type: "uint32" },
          { name: "startTime", type: "uint64" },
          { name: "planId", type: "uint256" },
          { name: "maxTotalAmount", type: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canExecute",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastPullTime",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mirrorDestinationChainId",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAccountPaused",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "importAccountState",
    inputs: [
      { name: "account", type: "address" },
      {
        name: "config",
        type: "tuple",
        components: [
          { name: "merchant", type: "address" },
          { name: "maxAmount", type: "uint256" },
          { name: "token", type: "address" },
          { name: "interval", type: "uint32" },
          { name: "startTime", type: "uint64" },
          { name: "planId", type: "uint256" },
          { name: "maxTotalAmount", type: "uint256" },
        ],
      },
      { name: "lastPullTime_", type: "uint64" },
      { name: "totalPulled_", type: "uint256" },
      { name: "mirrorDestinationChainId_", type: "uint256" },
      { name: "accountPaused_", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeMigration",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AutopayConfigured",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "maxAmount", type: "uint256", indexed: false },
      { name: "token", type: "address", indexed: false },
      { name: "interval", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AutopayConfigUpdated",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "previousPlanId", type: "uint256", indexed: true },
      { name: "newPlanId", type: "uint256", indexed: true },
      { name: "maxAmount", type: "uint256", indexed: false },
      { name: "interval", type: "uint32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PaymentExecuted",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BillingExecuted",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "planId", type: "uint256", indexed: false },
      { name: "reason", type: "uint8", indexed: false },
      { name: "grossAmount", type: "uint256", indexed: false },
      { name: "merchantAmount", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "AutopayRevoked",
    inputs: [{ name: "account", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "AccountStateImported",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "planId", type: "uint256", indexed: true },
      { name: "lastPullTime", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MigrationFinalized",
    inputs: [],
  },
] as const;

export const SessionVaultABI = [
  {
    type: "function",
    name: "fundSession",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "token", type: "address" },
    ],
    outputs: [{ name: "sessionId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "topUp",
    inputs: [
      { name: "sessionId", type: "bytes32" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settle",
    inputs: [
      { name: "sessionId", type: "bytes32" },
      { name: "amount", type: "uint256" },
      { name: "provider", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getBalance",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgentBalance",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSession",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "agent", type: "address" },
          { name: "token", type: "address" },
          { name: "balance", type: "uint256" },
          { name: "totalFunded", type: "uint256" },
          { name: "totalSettled", type: "uint256" },
          { name: "active", type: "bool" },
          { name: "createdAt", type: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAgentSessions",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedSettlers",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SessionFunded",
    inputs: [
      { name: "agent", type: "address", indexed: true },
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "token", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SessionSettled",
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "provider", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "SessionWithdrawn",
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "agent", type: "address", indexed: true },
    ],
  },
  {
    type: "function",
    name: "revokeMandate",
    inputs: [{ name: "mandateId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isMandateRevoked",
    inputs: [{ name: "mandateId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "revokedMandates",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "MandateRevoked",
    inputs: [
      { name: "mandateId", type: "bytes32", indexed: true },
      { name: "revoker", type: "address", indexed: true },
    ],
  },
] as const;

export const ZKUsageVerifierABI = [
  {
    type: "function",
    name: "setGroth16Verifier",
    inputs: [{ name: "verifier", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "groth16Verifier",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submitProof",
    inputs: [
      {
        name: "proof",
        type: "tuple",
        components: [
          { name: "a", type: "uint256[2]" },
          { name: "b", type: "uint256[2][2]" },
          { name: "c", type: "uint256[2]" },
        ],
      },
      {
        name: "inputs",
        type: "tuple",
        components: [
          { name: "agentAddress", type: "bytes32" },
          { name: "sessionId", type: "bytes32" },
          { name: "callCount", type: "uint256" },
          { name: "windowStart", type: "uint64" },
          { name: "windowEnd", type: "uint64" },
          { name: "merkleRoot", type: "bytes32" },
          { name: "nullifier", type: "bytes32" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isNullifierUsed",
    inputs: [{ name: "nullifier", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRateSchedule",
    inputs: [{ name: "planId", type: "uint256" }],
    outputs: [{ name: "ratePerCall", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingBalance",
    inputs: [{ name: "agent", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BillingSettled",
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "agentAddress", type: "bytes32", indexed: true },
      { name: "callCount", type: "uint256", indexed: false },
      { name: "settlementAmount", type: "uint256", indexed: false },
      { name: "windowStart", type: "uint64", indexed: false },
      { name: "windowEnd", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Groth16VerifierSet",
    inputs: [{ name: "verifier", type: "address", indexed: true }],
  },
] as const;

export const FeeCollectorABI = [
  // ── Core fee collection ──
  {
    type: "function",
    name: "collectSubscriptionFee",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "feeAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collectSettlementFee",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "feeAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  // ── Provider-specific fee collection ──
  {
    type: "function",
    name: "collectSubscriptionFeeFor",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "provider", type: "address" },
    ],
    outputs: [{ name: "feeAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collectSettlementFeeFor",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "provider", type: "address" },
    ],
    outputs: [{ name: "feeAmount", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  // ── Fee rate queries ──
  {
    type: "function",
    name: "subscriptionFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlementFeeRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProviderSubFeeBps",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProviderSettleFeeBps",
    inputs: [{ name: "provider", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  // ── Tier management ──
  {
    type: "function",
    name: "syncProviderTier",
    inputs: [
      { name: "provider", type: "address" },
      { name: "tier", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTierFeeRates",
    inputs: [
      { name: "tier", type: "uint8" },
      { name: "subFeeBps", type: "uint256" },
      { name: "settleFeeBps", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setProviderFeeRates",
    inputs: [
      { name: "provider", type: "address" },
      { name: "subFeeBps", type: "uint256" },
      { name: "settleFeeBps", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "tierSubFeeBps",
    inputs: [{ name: "tier", type: "uint8" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tierSettleFeeBps",
    inputs: [{ name: "tier", type: "uint8" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  // ── Treasury ──
  {
    type: "function",
    name: "accumulatedFees",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [{ name: "token", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // ── Events ──
  {
    type: "event",
    name: "FeeCollected",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "feeAmount", type: "uint256", indexed: false },
      { name: "feeType", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeesWithdrawn",
    inputs: [
      { name: "treasury", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ProviderFeeRateSet",
    inputs: [
      { name: "provider", type: "address", indexed: true },
      { name: "subFeeBps", type: "uint256", indexed: false },
      { name: "settleFeeBps", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ProviderTierSynced",
    inputs: [
      { name: "provider", type: "address", indexed: true },
      { name: "tier", type: "uint8", indexed: false },
      { name: "subFeeBps", type: "uint256", indexed: false },
      { name: "settleFeeBps", type: "uint256", indexed: false },
    ],
  },
] as const;

// ── MirrorRegistry ──────────────────────────────────────────

export const MirrorRegistryABI = [
  // Query functions (read-only)
  {
    type: "function",
    name: "isValid",
    inputs: [{ name: "subscriber", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMirror",
    inputs: [{ name: "subscriber", type: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "subscriber", type: "address" },
          { name: "planId", type: "uint256" },
          { name: "planTier", type: "string" },
          { name: "expiration", type: "uint64" },
          { name: "sourceChainId", type: "uint256" },
          { name: "sourceTokenId", type: "uint256" },
          { name: "sourceUpdatedAt", type: "uint64" },
          { name: "lastUpdated", type: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expiresAt",
    inputs: [{ name: "subscriber", type: "address" }],
    outputs: [{ name: "", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlanTier",
    inputs: [{ name: "subscriber", type: "address" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  // Events
  {
    type: "event",
    name: "SubscriptionMirrored",
    inputs: [
      { name: "subscriber", type: "address", indexed: true },
      { name: "sourceTokenId", type: "uint256", indexed: true },
      { name: "sourceChainId", type: "uint256", indexed: false },
      { name: "expiration", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoutedMessageProcessed",
    inputs: [
      { name: "messageId", type: "bytes32", indexed: true },
      { name: "route", type: "uint8", indexed: true },
    ],
  },
] as const;

// ── YieldSessionVault (ERC4626 yield-bearing session vault) ──────────────────

export const YieldSessionVaultABI = [
  {
    type: "function",
    name: "fundSession",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "sessionId", type: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeSession",
    inputs: [
      { name: "sessionId", type: "bytes32" },
      { name: "agent", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getSession",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "shares", type: "uint256" },
          { name: "depositedAssets", type: "uint256" },
          { name: "active", type: "bool" },
          { name: "createdAt", type: "uint64" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSessionBalance",
    inputs: [{ name: "sessionId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "yieldStrategy",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SessionCreated",
    inputs: [
      { name: "agent", type: "address", indexed: true },
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "shares", type: "uint256", indexed: false },
      { name: "assets", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SessionSettled",
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "provider", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SessionClosed",
    inputs: [
      { name: "sessionId", type: "bytes32", indexed: true },
      { name: "sharesRedeemed", type: "uint256", indexed: false },
      { name: "assetsReturned", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "YieldHarvested",
    inputs: [{ name: "amount", type: "uint256", indexed: false }],
  },
] as const;
